### ISSUE TITLE
Initial Setup of non mvx plugin

### ISSUE THREAD

**Issue by smstuebe** [xabre/MvvmCross-BluetoothLE#19]
- [x] setup projects
- [x] move code to Common library

**Comment by xabre** [comment]
I see you are doing a lot of structural changes. I'll refrain from changing anything in these files so that we avoid conflicts. Let me know when you are ready to merge this branch back into master.

**Comment by xabre** [comment]
Moved the ios and android implementations to Plugin.Ble.*

**Comment by smstuebe** [comment]
Assignee: sms ^^ iwas working on this. we should talk. Where are you today? come to work.
